### ISSUE TITLE
N/N12/err.txt  这个不应该有啊

### ISSUE THREAD

**Issue by shijinkui** [cbeta-org/xml-p5#3]
https://github.com/cbeta-org/xml-p5/blob/master/N/N12/err.txt

**Comment by mahawu** [comment]
謝謝指出這個錯誤。我們會處理的。

2015-10-25 23:06 GMT+08:00 时金魁 <notifications@github.com>:

> https://github.com/cbeta-org/xml-p5/blob/master/N/N12/err.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeta-org/xml-p5/issues/3>.
>



-- 
吳寶原 Maha Wu
中華電子佛典協會(CBETA) <http://www.cbeta.org/>
CBETA Facebook <https://www.facebook.com/cbeta.org> / Maha Facebook
<https://www.facebook.com/maha1963>

**Comment by shijinkui** [comment]
@mahawu  读了这篇文章http://www.cbeta.org/data/cbeta10y/cbhistory.htm  看到cbeta背后工作的不易，超级赞。目前我正写点代码，把xmk-p5转成json、markdown等格式，licence用的apache V2. 看有无版权问题。这是样本：https://github.com/sutras/sutra-fmt/blob/master/src/main/resources/%E4%BD%9B%E8%AA%AA%E5%A6%99%E8%89%B2%E7%8E%8B%E5%9B%A0%E7%B7%A3%E7%B6%93.json

https://github.com/sutras/sutra-fmt/blob/master/src/main/resources/%E4%BD%9B%E8%AA%AA%E5%A6%99%E8%89%B2%E7%8E%8B%E5%9B%A0%E7%B7%A3%E7%B6%93.markdown

**Comment by cbeta-org** [comment]
CBETA 經文的版權宣告在此

http://www.cbeta.org/copyright.php

只要符合此規範，就沒有問題了。

**Comment by shijinkui** [comment]
no problem
